# Generated by Django 3.2.6 on 2021-08-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210823_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vato_ratio',
            new_name='vote_ratio',
        ),
    ]
