# Generated by Django 3.2.6 on 2021-08-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_vato_ratio_project_vote_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo',
            new_name='demo_link',
        ),
    ]
